modLoader="javafml"
loaderVersion="[46,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/Coloryr/AllMusic_Client/issues"

[[mods]]
modId="allmusic_client"
version="${version}"
displayName="AllMusic Client"
displayURL="https://github.com/Coloryr/AllMusic_Client"
logoFile="icon.png"
authors="Color_yr"
description='''AllMusic Client Mod'''

[[dependencies.allmusic_client]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="CLIENT"

[[dependencies.allmusic_client]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="CLIENT"