rmdir "folia/src/main/java/coloryr/allmusic/core"
rmdir "server/src/main/java/coloryr/allmusic/core"
rmdir "server_top/src/main/java/coloryr/allmusic/core"
rmdir "forge_1_20/src/main/java/coloryr/allmusic/core"
rmdir "forge_1_19_3/src/main/java/coloryr/allmusic/core"
rmdir "forge_1_19_2/src/main/java/coloryr/allmusic/core"
rmdir "forge_1_18_2/src/main/java/coloryr/allmusic/core"
rmdir "forge_1_16_5/src/main/java/coloryr/allmusic/core"
rmdir "fabric_1_20/src/main/java/coloryr/allmusic/core"
rmdir "fabric_1_19_3/src/main/java/coloryr/allmusic/core"
rmdir "fabric_1_19_2/src/main/java/coloryr/allmusic/core"
rmdir "fabric_1_18_2/src/main/java/coloryr/allmusic/core"
rmdir "fabric_1_16_5/src/main/java/coloryr/allmusic/core"

rmdir /s /q "folia/src/main/resources/core"
rmdir /s /q "server/src/main/resources/core"
rmdir /s /q "server_top/src/main/resources/core"
rmdir /s /q "forge_1_20/src/main/resources/core"
rmdir /s /q "forge_1_19_3/src/main/resources/core"
rmdir /s /q "forge_1_19_2/src/main/resources/core"
rmdir /s /q "forge_1_18_2/src/main/resources/core"
rmdir /s /q "forge_1_16_5/src/main/resources/core"
rmdir /s /q "fabric_1_20/src/main/resources/core"
rmdir /s /q "fabric_1_19_3/src/main/resources/core"
rmdir /s /q "fabric_1_19_2/src/main/resources/core"
rmdir /s /q "fabric_1_18_2/src/main/resources/core"
rmdir /s /q "fabric_1_16_5/src/main/resources/core"

rmdir /s /q "folia/build"
rmdir /s /q "server/build"
rmdir /s /q "server_top/build"
rmdir /s /q "forge_1_20/build"
rmdir /s /q "forge_1_19_3/build"
rmdir /s /q "forge_1_19_2/build"
rmdir /s /q "forge_1_18_2/build"
rmdir /s /q "forge_1_16_5/build"
rmdir /s /q "fabric_1_19_3/build"
rmdir /s /q "fabric_1_19_2/build"
rmdir /s /q "fabric_1_18_2/build"
rmdir /s /q "fabric_1_16_5/build"

rmdir /s /q "folia/.gradle"
rmdir /s /q "server/.gradle"
rmdir /s /q "server_top/.gradle"
rmdir /s /q "forge_1_20/.gradle"
rmdir /s /q "forge_1_19_3/.gradle"
rmdir /s /q "forge_1_19_2/.gradle"
rmdir /s /q "forge_1_18_2/.gradle"
rmdir /s /q "forge_1_16_5/.gradle"
rmdir /s /q "fabric_1_20/.gradle"
rmdir /s /q "fabric_1_19_3/.gradle"
rmdir /s /q "fabric_1_19_2/.gradle"
rmdir /s /q "fabric_1_18_2/.gradle"
rmdir /s /q "fabric_1_16_5/.gradle"