rmdir "server/src/main/java/coloryr/allmusic/core"
rmdir "forge_1_19_3/src/main/java/coloryr/allmusic/core"
rmdir "forge_1_18_2/src/main/java/coloryr/allmusic/core"
rmdir "forge_1_16_5/src/main/java/coloryr/allmusic/core"
rmdir "fabric_1_19_3/src/main/java/coloryr/allmusic/core"
rmdir "fabric_1_19_2/src/main/java/coloryr/allmusic/core"
rmdir "fabric_1_18_2/src/main/java/coloryr/allmusic/core"
rmdir "fabric_1_16_5/src/main/java/coloryr/allmusic/core"

rmdir "server/build"
rmdir "forge_1_19_3/build"
rmdir "forge_1_18_2/build"
rmdir "forge_1_16_5/build"
rmdir "fabric_1_19_3/build"
rmdir "fabric_1_19_2/build"
rmdir "fabric_1_18_2/build"
rmdir "fabric_1_16_5/build"

rmdir "server/.gradle"
rmdir "forge_1_19_3/.gradle"
rmdir "forge_1_18_2/.gradle"
rmdir "forge_1_16_5/.gradle"
rmdir "fabric_1_19_3/.gradle"
rmdir "fabric_1_19_2/.gradle"
rmdir "fabric_1_18_2/.gradle"
rmdir "fabric_1_16_5/.gradle"