modLoader="javafml"
loaderVersion="[2,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/Coloryr/AllMusic_Server/issues"

[[mods]]
modId="allmusic_server"
version="${version}"
displayName="AllMusic Server"
displayURL="https://github.com/Coloryr/AllMusic_Server/"
logoFile="icon.png"
authors="Color_yr"
description='''AllMusic Server Mod'''

[[dependencies.allmusic_server]]
modId="neoforge"
type="required"
versionRange="[21.11.17-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.allmusic_server]]
modId="minecraft"
type="required"
versionRange="[1.21.11]"
ordering="NONE"
side="BOTH"