modLoader="javafml"
loaderVersion="[2,)"
license="GPL-3.0"

[[mods]]
modId="allmusic"
version="${version}"
displayName="AllMusic Server"
authors="Color_yr"
description='''AllMusic Server Mod'''

[[dependencies.allmusic]]
modId="neoforge"
type="required"
versionRange="[21.11.17-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.allmusic]]
modId="minecraft"
type="required"
versionRange="[1.21.11]"
ordering="NONE"
side="BOTH"