modLoader="javafml"
loaderVersion="[2,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/Coloryr/AllMusic_Client/issues"

[[mods]]
modId="allmusic"
version="${version}"
displayName="AllMusic Client"
displayURL="https://github.com/Coloryr/AllMusic_Client/"
logoFile="icon.png"
authors="Color_yr"
description='''AllMusic Client Mod'''

[[mods]]
modId="allmusic_client"
version="${version}"
displayName="AllMusic Client"
displayURL="https://github.com/Coloryr/AllMusic_Client/"
logoFile="icon.png"
authors="Color_yr"
description='''AllMusic Client Mod'''

[[dependencies.allmusic_client]]
modId="neoforge"
type="required"
versionRange="[21.6.20-beta,)"
ordering="NONE"
side="CLIENT"

[[dependencies.allmusic_client]]
modId="minecraft"
type="required"
versionRange="[1.21.6]"
ordering="NONE"
side="CLIENT"