modLoader="javafml"
loaderVersion="[2,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/Coloryr/AllMusic_Server/issues/"

[[mods]]
modId="allmusic"
version="${version}"
displayName="AllMusic Server"
displayURL="https://github.com/Coloryr/AllMusic_Server/"
logoFile="icon.png"
authors="Color_yr"
description='''AllMusic Server Mod'''

[[dependencies.allmusic]]
modId="neoforge"
type="required"
versionRange="[21.0.167,)"
ordering="NONE"
side="BOTH"

[[dependencies.allmusic]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.1)"
ordering="NONE"
side="BOTH"